openapi: "3.0.3"
info:
  title: "Application API"
  description: "Application API"
  version: "1.0.0"
servers:
  - url: "https://tsm-input-dolly.intern.dev.nav.no"
  - url: "http://tsm-input-dolly.tsm"
paths:
  /api/sykmelding:
    post:
      operationId: opprettSykmelding
      tags:
        - Sykmelding
      summary: Opprett sykmelding
      requestBody:
        $ref: '#/components/requestBodies/SykmeldingBody'
      responses:
        '200':
          $ref: '#/components/responses/SykmeldingResponse'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /api/sykmelding/{sykmeldingId}:
    parameters:
      - name: sykmeldingId
        in: path
        required: true
        schema:
          type: string
        description: SykmeldingId
    get:
      operationId: getSykmeldingById
      summary: Get sykmelding by id
      responses:
        '200':
          $ref: '#/components/responses/SykmeldingResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /api/sykmelding/ident:
    parameters:
      - name: X-ident
        in: header
        required: true
        schema:
          $ref: '#/components/schemas/Ident'
        description: Ident
    get:
      operationId: getSykmeldingerByIdent
      summary: Get sykmeldinger by ident (FNR or DNR)
      responses:
        '200':
          $ref: '#/components/responses/SykmeldingerResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
    delete:
      parameters:
        - name: X-ident
          in: header
          required: true
          schema:
            $ref: '#/components/schemas/Ident'
          description: Ident
      operationId: deleteSykmeldingerByIdent
      summary: Delete sykmeldinger by ident (FNR or DNR)
      responses:
        '200':
          description: OK
        '500':
          $ref: '#/components/responses/ErrorResponse'

components:
  requestBodies:
    SykmeldingBody:
      description: "Opprett sykmelding"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Sykmelding'
  responses:
    ErrorResponse:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NotFoundResponse'
      description: "Sykmelding not found"
    SykmeldingResponse:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SykmeldingResponse'
      description: "Response with sykmeldingId"
    SykmeldingerResponse:
      description: "List of sykmeldinger"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SykmeldingerResponse'
  schemas:
    NotFoundResponse:
      type: object
      properties:
        message:
          type: string
    Date:
      type: string
      format: date
    SykmeldingId:
      type: string
    Ident:
      type: string
      pattern: "^[0-9]{11}$"
      example: "62858801562"
      description: "FNR eller DNR"
    SykmeldingResponse:
      type: object
      properties:
        sykmeldingId:
          $ref: '#/components/schemas/SykmeldingId'
        aktivitet:
          $ref: '#/components/schemas/AktivitetList'
        ident:
          $ref: '#/components/schemas/Ident'
    SykmeldingerResponse:
      type: object
      properties:
        sykmeldinger:
          type: array
          items:
            $ref: '#/components/schemas/SykmeldingResponse'
    Sykmelding:
      type: object
      properties:
        ident:
          $ref: '#/components/schemas/Ident'
        aktivitet:
          $ref: '#/components/schemas/AktivitetList'
      required:
        - ident
        - aktivitet
    AktivitetList:
      type: array
      items:
        $ref: '#/components/schemas/Aktivitet'
    Grad:
      type: integer
      minimum: 1
      maximum: 99
      nullable: true
      description: valgfri grad av sykmelding i %. uten denne er den ansett til å være 100% sykmelding
    Aktivitet:
      type: object
      example: { fom: "2025-01-01", tom: "2025-01-02"}
      properties:
        grad:
          $ref: '#/components/schemas/Grad'
        fom:
          $ref: '#/components/schemas/Date'
        tom:
          $ref: '#/components/schemas/Date'
      required:
        - fom
        - tom
