openapi: "3.0.3"
info:
  title: "Application API"
  description: "Application API"
  version: "1.0.0"
servers:
  - url: "http://0.0.0.0:8080"
paths:
  /sykmelding:
    post:
      operationId: opprettSykmelding
      tags:
        - Sykmelding
      summary: Opprett sykmelding
      requestBody:
        $ref: '#/components/requestBodies/SykmeldingBody'
      responses:
        '200':
          $ref: '#/components/responses/CreateSykmeldingResponse'
        '500':
          description: Internal server error
components:
  requestBodies:
    SykmeldingBody:
      description: "Opprett sykmelding"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Sykmelding'
  responses:
    CreateSykmeldingResponse:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateResponse'
      description: "Response with sykmeldingId"
  schemas:
    Date:
      type: string
      format: date
    CreateResponse:
      type: object
      allOf:
        - $ref: '#/components/schemas/Sykmelding'
      properties:
        sykmeldingId:
          type: string
          format: uuid
      required:
        - sykmeldingId
    Sykmelding:
      type: object
      properties:
        ident:
          type: string
          minLength: 11
          maxLength: 11
          example: "62858801562"
          description: "FNR eller DNR"
        aktivitet:
          $ref: '#/components/schemas/Aktivitet'
      required:
        - ident
        - aktivitet
    Aktivitet:
      type: object
      properties:
        fom:
          $ref: '#/components/schemas/Date'
        tom:
          $ref: '#/components/schemas/Date'
      #        type:
      #          type: string
      #          enum:
      #            - AKTIVITET_IKKE_MULIG
      #            - AVVENTENDE,
      #            - BEHANDLINGSDAGER,
      #            - GRADERT,
      #            - REISETILSKUDD
      required:
        - fom
        - tom
