---
apiVersion: data.nais.io/v1
kind: Postgres
metadata:
  name: tsm-input-dolly-postgres-cluster
  namespace: tsm
spec:
  cluster:
    majorVersion: "17"
    resources:
      cpu: 50m
      diskSize: 3Gi
      memory: 1G
---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tsm-input-dolly
  namespace: tsm
  labels:
    team: tsm
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  gcp:
    sqlInstances:
      - type: POSTGRES_18
        name: tsm-input-dolly
        cascadingDelete: false
        databases:
          - name: tsm-input-dolly
        diskAutoresize: false
        diskType: SSD
        tier: db-f1-micro
  postgres:
    clusterName: tsm-input-dolly-postgres-cluster
  filesFrom:
    - emptyDir:
        medium: Memory
      mountPath: /app/docs
  liveness:
    path: /internal/is_alive
  readiness:
    path: /internal/is_ready
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    requests:
      cpu: 30m
      memory: 128Mi
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  kafka:
    pool: nav-dev
  ingresses:
    - "https://tsm-input-dolly.intern.dev.nav.no/openapi"
    - "https://tsm-input-dolly.intern.dev.nav.no/swagger-ui"
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  accessPolicy:
    outbound:
      rules:
        - application: tsm-pdl-cache
    inbound:
      rules:
        - application: teamsykmelding-mock
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: testnav-sykemelding-proxy-trygdeetaten
          namespace: dolly
          cluster: dev-gcp
        - application: testnav-sykemelding-proxy
          namespace: dolly
          cluster: dev-gcp
