apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tsm-input-dolly
  namespace: tsm
  labels:
    team: tsm
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  filesFrom:
    - emptyDir:
        medium: Memory
      mountPath: /app/docs
  liveness:
    path: /internal/is_alive
  readiness:
    path: /internal/is_ready
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    requests:
      cpu: 30m
      memory: 128Mi
  kafka:
    pool: nav-dev
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
