[versions]
kotlin = "2.4.10"
logback = "1.5.38"
logbackEncoder = "9.0"
flyway = "11.12.0"
sykmeldingInput = "27"
micrometer = "1.6.13"
postgresVersion = "42.7.7"
testcontainerVersion = "2.0.3"
mockkVersion = "1.14.5"
mockitoVersion = "5.4.0"
kotlinxCoroutinesTestVersion = "1.10.2"
hamcrestVersion = "3.0"
restAssuredVersion = "5.5.6"
swaggerValidatorResetAssuredVersion = "2.45.1"
kotest-assertions = "6.1.11"

[libraries]
postgres = { module = "org.postgresql:postgresql", version.ref = "postgresVersion" }
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flyway-postgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logback-encoder = { module = "net.logstash.logback:logstash-logback-encoder", version.ref = "logbackEncoder"}
micrometer-registry-prometheus = { module = "io.micrometer:micrometer-registry-prometheus", version.ref = "micrometer" }

tsm-sykmelding-input = { module = "no.nav.tsm.sykmelding:input", version.ref = "sykmeldingInput" }

kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest-assertions" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
testcontainers-postgresql = { module = "org.testcontainers:testcontainers-postgresql", version.ref = "testcontainerVersion" }
mockk = { module = "io.mockk:mockk" , version.ref = "mockkVersion"}
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin" , version.ref = "mockitoVersion"}
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test" , version.ref = "kotlinxCoroutinesTestVersion"}
hamcrest = { module = "org.hamcrest:hamcrest", version.ref = "hamcrestVersion" }
rest-assured = { module = "io.rest-assured:rest-assured", version.ref = "restAssuredVersion" }
swagger-request-validator-rest-assured = { module = "com.atlassian.oai:swagger-request-validator-restassured", version.ref = "swaggerValidatorResetAssuredVersion" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
flyway = { id = "org.flywaydb.flyway", version.ref = "flyway" }
