[versions]
kotlin = "2.4.10"
flyway = "13.0.0"
postgres = "42.7.13"

logback = "1.6.1"
logbackEncoder = "9.0"

tsm-sykmeldinger-input = "29"

testcontainers = "2.0.5"
mockkVersion = "1.14.11"
kotlinxCoroutinesTest = "1.11.0"
restAssured = "6.0.1"
swaggerValidatorResetAssured = "3.0.0"
kotest-assertions = "6.2.3"

[libraries]
postgres = { module = "org.postgresql:postgresql", version.ref = "postgres" }
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flyway-postgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }

logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logback-encoder = { module = "net.logstash.logback:logstash-logback-encoder", version.ref = "logbackEncoder"}

tsm-sykmeldinger-input = { module = "no.nav.tsm.sykmelding:input", version.ref = "tsm-sykmeldinger-input" }

kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest-assertions" }
testcontainers-postgresql = { module = "org.testcontainers:testcontainers-postgresql", version.ref = "testcontainers" }
mockk = { module = "io.mockk:mockk" , version.ref = "mockkVersion"}
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test" , version.ref = "kotlinxCoroutinesTest" }
rest-assured = { module = "io.rest-assured:rest-assured", version.ref = "restAssured" }
swagger-request-validator-rest-assured = { module = "com.atlassian.oai:swagger-request-validator-restassured", version.ref = "swaggerValidatorResetAssured" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
flyway = { id = "org.flywaydb.flyway", version.ref = "flyway" }
