[versions]
kotlin = "2.4.10"
flyway = "13.0.0"
postgresVersion = "42.7.13"

logback = "1.5.38"
logbackEncoder = "9.0"
micrometer = "1.17.0"
khealth = "3.0.2"

sykmeldingInput = "27"

testcontainerVersion = "2.0.5"
mockkVersion = "1.14.11"
mockitoVersion = "6.3.0"
kotlinxCoroutinesTestVersion = "1.11.0"
hamcrestVersion = "3.0"
restAssuredVersion = "6.0.1"
swaggerValidatorResetAssuredVersion = "3.0.0"
kotest-assertions = "6.2.3"

[libraries]
postgres = { module = "org.postgresql:postgresql", version.ref = "postgresVersion" }
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flyway-postgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }

logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logback-encoder = { module = "net.logstash.logback:logstash-logback-encoder", version.ref = "logbackEncoder"}
micrometer-registry-prometheus = { module = "io.micrometer:micrometer-registry-prometheus", version.ref = "micrometer" }
khealth = { module = "dev.hayden:khealth", version.ref = "khealth" }

tsm-sykmelding-input = { module = "no.nav.tsm.sykmelding:input", version.ref = "sykmeldingInput" }

kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest-assertions" }
testcontainers-postgresql = { module = "org.testcontainers:testcontainers-postgresql", version.ref = "testcontainerVersion" }
mockk = { module = "io.mockk:mockk" , version.ref = "mockkVersion"}
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin" , version.ref = "mockitoVersion"}
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test" , version.ref = "kotlinxCoroutinesTestVersion"}
hamcrest = { module = "org.hamcrest:hamcrest", version.ref = "hamcrestVersion" }
rest-assured = { module = "io.rest-assured:rest-assured", version.ref = "restAssuredVersion" }
swagger-request-validator-rest-assured = { module = "com.atlassian.oai:swagger-request-validator-restassured", version.ref = "swaggerValidatorResetAssuredVersion" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
flyway = { id = "org.flywaydb.flyway", version.ref = "flyway" }
